[package]
name = "jxl-winthumb"
version = "0.1.13"
authors = ["Kagami Sascha Rosylight <saschanaz@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-logging = "2.0.2"
log = "0.4.14"
kagamijxl = "0.3.1"
winreg = "0.10.1"
windows = "0.21.1"

[build-dependencies]
windows = "0.21.1"
