[package]
name = "jxl-winthumb"
version = "0.1.10"
authors = ["Kagami Sascha Rosylight <saschanaz@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-logging = "2.0.2"
log = "0.4.14"
kagamijxl = "0.2.8"
image = "0.23.14"
winreg = "0.9.0"
windows = "0.20.1"

[build-dependencies]
windows = "0.20.1"
