[package]
name = "jxl-winthumb"
version = "0.1.4"
authors = ["Kagami Sascha Rosylight <saschanaz@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intercom = { git = "https://github.com/Rantanen/intercom", rev = "41518eef1dd6984c130d6daf2218b9fb6e47c3bb" }
simple-logging = "2.0.2"
log = "0.4.14"
kagamijxl = "0.2.7"
image = "0.23.14"
winreg = "0.8.0"
windows = "0.9.1"

[build-dependencies]
windows = "0.9.1"
